### PR TITLE
upgrade python to 3.10

### PR DESCRIPTION
**Pull request by bluquar**

### CODE REVIEW

**Comment by lowellbander** [comment]
Ooo what's in 3.10 that we need?

Also, surprised I can merge without reviewing, gonna give it a whirl

**Comment by bluquar** [comment]
There's nothing we need. It's just that I switched over to my other computer, which didn't have Python 3 installed yet at all, so I downloaded it and thus got the latest version installed. And then pip started warning me that my machine's python version didn't match the project's python version.

**Comment by bluquar** [comment]
The reason you could merge without reviewing was because the base branch was `setup-graphene` rather than `main`

**Comment by lowellbander** [comment]
Oh interesting! Got it!

**Pull request merged**
